services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: recsys-nacos
    environment:
      MODE: standalone
      NACOS_AUTH_ENABLE: "false"
      JVM_XMS: 256m
      JVM_XMX: 512m
      JVM_XMN: 128m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    restart: unless-stopped
