package com.recsys.domain.saga;

public enum SagaEventType {
    SAGA_STARTED,
    STEP_STARTED,
    STEP_COMPLETED,
    TRY_STARTED,
    TRY_COMPLETED,
    CONFIRM_STARTED,
    CONFIRM_COMPLETED,
    CANCEL_STARTED,
    CANCEL_COMPLETED,
    COMPENSATION_STARTED,
    COMPENSATION_COMPLETED,
    SAGA_COMPLETED,
    SAGA_FAILED
}
