apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - redis-cluster.yaml
  - catalog-serving.yaml
  - model-serving.yaml
  - online-serving.yaml
  - api-gateway.yaml
  - pdb.yaml
  - hpa.yaml
  - network-policy.yaml
  - servicemonitor.yaml
images:
  - name: recsys-backend-service
    newTag: local
